name: Generate Pacman

on:
  schedule:
    - cron: "0 */12 * * *"

  workflow_dispatch:

jobs:
  generate:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Generate Pacman contribution graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: carlosvinicius0293-droid

      - name: Push to pacman-output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: pacman-output
          publish_dir: ./
